# Generated by Django 5.2 on 2025-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAnalysis', '0003_remove_webpage_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='time_entered',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
