# Generated by Django 5.2 on 2025-04-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAnalysis', '0004_webpage_time_entered_webpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='time_entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
