# Generated by Django 5.2 on 2025-04-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAnalysis', '0005_alter_webpage_time_entered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='time_entered',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='virustotal_report',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
